# Generated by Django 4.1.5 on 2023-01-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
